version: '3.8'
services:
  rundeck:
    image: rundeck/rundeck:4.14.0
    ports:
      - "4440:4440"
    environment:
      - RUNDECK_GRAILS_URL=http://localhost:4440
      - RUNDECK_SERVER_ADDRESS=0.0.0.0
    volumes:
      - rundeck_data:/home/rundeck/server/data
    restart: unless-stopped

volumes:
  rundeck_data: